<html>
<!--Automatically generated with XSLT--><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>omniORBpy 2.5 bugs</title>
<link rel="stylesheet" href="../styles.css" type="text/css">
</head>
<body link="#0000ff" vlink="#000080" bgcolor="#ffffff" alink="#ff0000" text="#000000"><table border="0" width="100%" cellspacing="5" cellpadding="10">
<tr>
<td width="15%" class="header"><img src="../img/omniORBlogo.gif" width="122" height="92"></td>
<td class="header"><h1 align="center">omniORBpy 2.5 bugs</h1></td>
</tr>
<tr>
<td width="15%" class="sidebar" valign="top" align="left">
<p align="center"><b>Destinations</b></p>
<a href="../index.html">omniORB home</a><br><a href="../history.html">History</a><br><a href="../features.html">Features</a><br><a href="../download.html">Download</a><br><a href="../docs.html">Documentation</a><br><a href="/cgi-bin/moin.cgi">Wiki</a><br><a href="/cgi-bin/moin.cgi/FrequentlyAskedQuestions">FAQ</a><br><a href="../bugs.html">Bugs</a><br><a href="../development.html">Development</a><br><a href="../snapshots/">CVS snapshots</a><br><a href="http://sourceforge.net/projects/omniorb/">SF project</a><br><a href="../list.html">Mailing list</a><br><a href="../links.html">Links</a><br><a href="http://www.omniorb-support.com/">Support</a><br><a href="../contact.html">Contact</a><br><br><hr width="80%">
<p align="center"><a href="http://sourceforge.net"><img src="http://sourceforge.net/sflogo.php?group_id=51138&amp;type=1" width="88" height="31" border="0" alt="SourceForge.net    Logo"></a><br><img src="http://grisby.dyndns.org/cgi-bin/count?omni/bugs/2.5" width="1" height="1" alt=""></p>
</td>
<td class="main" valign="top" align="left">
<p>
	  The following bugs in omniORBpy 2.5 have been fixed. Update from <a href="../development.html">CVS</a> to get the fixes.
        </p>
<table align="center" width="95%">
<tr><td colspan="2"><hr></td></tr>

<tr>
<td>Summary:</td>
<td>
<b>ULong sequence / array marshalling bug</b>
            (bug number 1)
            <a name="bug1"></a>
</td>
</tr>
<tr>
<td>Date:      </td>
<td>Mon Dec 20 17:20:40 GMT 2004</td>
</tr>
  
  <tr>
<td>Reported by:</td>
<td>Teemu Torma</td>
</tr>
  <tr valign="top">
<td>Description:</td>
<td>
  The code to deal with tuples as sequences or arrays of unsigned
  longs was incorrect.
  </td>
</tr>
<tr><td colspan="2"><hr></td></tr>

<tr>
<td>Summary:</td>
<td>
<b>Race condition in thread cache</b>
            (bug number 2)
            <a name="bug2"></a>
</td>
</tr>
<tr>
<td>Date:      </td>
<td>Mon Jan 24 17:23:41 GMT 2005</td>
</tr>
  
  <tr valign="top">
<td>Description:</td>
<td>
  Very rare case of a race between the thread cache and Python worker
  thread creation.
  </td>
</tr>
<tr><td colspan="2"><hr></td></tr>

<tr>
<td>Summary:</td>
<td>
<b>Improper thread state reuse</b>
            (bug number 3)
            <a name="bug3"></a>
</td>
</tr>
<tr>
<td>Date:      </td>
<td>Tue Feb 22 10:58:25 GMT 2005</td>
</tr>
  
  <tr valign="top">
<td>Description:</td>
<td>
  On Python &gt;= 2.3, the thread state cache could incorrectly cache
  thread state for a thread that had exited, and a new one started
  with the same id.
  </td>
</tr>
<tr><td colspan="2"><hr></td></tr>

</table>
</td>
</tr>
</table></body>
</html>
